<a href="https://colab.research.google.com/github/RajarshiRoychoudhury/Machine-Learning-with-applictions-in-NLP/blob/master/sentiment_polarity_comparison_meta.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import csv
import os
from xml.etree import ElementTree

In [ ]:
pip install wxconv

     |████████████████████████████████| 5.8MB 12.8MB/s 
     |████████████████████████████████| 102kB 12.9MB/s 


In [ ]:
pip install -q pyyaml h5py

In [ ]:

from wxconv import WXC
from wxconv import WXC
con = WXC(order='utf2wx')
hin="एंड्रॉयड 4.4.4 से ऊपर के वर्जन पर करता है काम ।"
print(con.convert(hin))

eMdrOYyada 4.4.4 se Upara ke varjana para karawA hE kAma .


In [ ]:
def generate_csv(filename):
  tree = ElementTree.parse(filename)
  root=tree.getroot()
  data_file = open("review_sentiment.csv",mode="w",encoding="utf-8")
  csv_writer = csv.writer(data_file)
  col_names=["text","polarity"]
  csv_writer.writerow(col_names)
  mapping= {
    "positive":1,
    "negative":2,
    "neutral":0,
    "conflict":3,
  }
  for sentence in root:
    row = []
    #row.append(sentence.find("text").text)
    text_uncleaned = sentence.find("text").text
    if not text_uncleaned:
      continue
    #print(text_uncleaned)
    text=""
    avoid_dict = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '0','1', '2', '3', '4', '5', '6', '7', '8', '9', '!', '#','.',',','/','?','<','.','!','@','#','$','%','^','&','*','(',')','{','}','[',']',':',';','>','']
    for char in text_uncleaned:
      if str(char) not in avoid_dict:
        text+=char
    row.append(con.convert(text))
  #print(sentence.attrib["polarity"])
    if(row[0]!=None):
      row.append(mapping[sentence.attrib["polarity"]])
      csv_writer.writerow(row)
  data_file.close()

In [ ]:
generate_csv(filename = "ReviewSentimentDataset-SentenceClassification.xml")

In [ ]:
def load_dataset(filename):
  df=pd.read_csv(filename)
  print(df.head(10))
  return df

In [ ]:
df = load_dataset("review_sentiment.csv")

                                                text  polarity
0  Pesabuka kA sikyoritI cEkaapa PIcara pOYpaapa ...         0
1  isa pOYpaapa bOYksa meM pAsavarda ceMja karane...         0
2  Apa yahIM se purAne lOYgaina seSaMsa ko hameSA...         0
3  Ese meM kaI bAra EsA howA hE ki ApakA lOYgaina...         0
4  aba nae PIcara se isa waraha kI galawiyAM nahI...         1
5  eMdrOYyada  se Upara ke varjana para karawA hE...         0
6     eMdrOYyada  kitakEta yA usase Upara ke varj...         0
7  kaMpanI ke muwAbika  eMdrOYyada ke lie Ae peri...         1
8  periskopa ke eMdrOYyada varjana meM kuCa eVse ...         0
9  isameM meteriyala inspAyarda dijAina hE jo eMd...         0


In [ ]:
def prepare_dataset(filename,lang):
  df1=pd.read_csv(filename+"_POS.txt",sep="\t")
  df2=pd.read_csv(filename+"_NEG.txt",sep="\t")
  df3=pd.read_csv(filename+"_NEU.txt",sep="\t")
  df1.drop("None",axis=1,inplace=True)
  df1["sentiment"]=1
  df2.drop("None",axis=1,inplace=True)
  df2["sentiment"]=2
  df3.drop("None",axis=1,inplace=True)
  df3["sentiment"]=0
  #df1=df1[:2000]
  df2=df2[:2300]
  #df3=df3[:350]
  df=df1.append(df2)
  df=df.append(df3)
  df.index=np.arange(0,len(df.Word))
  for i in range (len(df)):
    con = WXC(order='utf2wx',lang=lang)
    a=con.convert(str(df.Word[i]))
    df.iloc[i,1]=a
    if i<5:
      print(df.Word[i])
  return df

In [ ]:
df_beng=prepare_dataset("BN","ben")
df_tamil=prepare_dataset("TA","tam")
df_telegu=prepare_dataset("TE","tel")

akalafka
akqwrima
aklAnwa
akRayZa
aKaNda
akkarYE_arYrYa
acal
acAwAraNamAnYawu
acuwwamAnYa
acEkka
aMkiwaBAvaM
aMxamEna
akRarAsyulu
awi_kopiRti
awi_curukEna


In [ ]:
df_beng=df_beng.append(df_telegu)
df_beng=df_beng.append(df_tamil)
df=df_beng
df.index=np.arange(0,len(df.Word))
df

Type          Word  sentiment
0        a      akalafka          1
1        a      akqwrima          1
2        a       aklAnwa          1
3        a       akRayZa          1
4        a        aKaNda          1
...    ...           ...        ...
14114    v         vinYE          0
14115    v       vimAnYa          0
14116    v       viRayam          0
14117    v  veVrYum_Ukam          0
14118    v   hipnYAticam          0

[14119 rows x 3 columns]

In [ ]:
df_text=pd.read_csv("review_sentiment.csv")
df_text

text  polarity
0     Pesabuka kA sikyoritI cEkaapa PIcara pOYpaapa ...         0
1     isa pOYpaapa bOYksa meM pAsavarda ceMja karane...         0
2     Apa yahIM se purAne lOYgaina seSaMsa ko hameSA...         0
3     Ese meM kaI bAra EsA howA hE ki ApakA lOYgaina...         0
4     aba nae PIcara se isa waraha kI galawiyAM nahI...         1
...                                                 ...       ...
5412  yAnI  digrI eMgala se BI pikcara sAPa najara A...         1
5413    ye tIvI  grAPiksa iMjana ko saporta karawI hE .         1
5414                             isameM   dikodara hE .         0
5415  sAWa hI  vAI - PAI   netavarka iWaraneta porta...         1
5416  ye tebala stEMda Ora vOYla stEMda xonoM ke sAW...         0

[5417 rows x 2 columns]

In [ ]:
d={}
string_list=list("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz")
for i in range(len(string_list)):
  l=[0 for j in range(len(string_list))]
  l[i]=1
  d[string_list[i]]=np.array(l)
print(d['A'])

[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [ ]:
def extract(df,string_list=string_list):
  maxim=0
  X=df.Word.values
  for i in range(len(X)):
      l=[]
      string=str(X[i])
      if len(string)>maxim:
        maxim=len(string)
      l2=string.split("_")
      l=[]
      #print(len(string)),print(string)
      for k in l2:
        for j in range(len(k)):
          if k[j]!="-":
            try:
              #print(k[j])
              index=string_list.index(k[j])
              l.append(index)
            except:
              continue
      l=np.array(l)
      X[i]=l
  return X

In [ ]:
import tensorflow as tf
X=extract(df)
print(X)
X_train=tf.keras.preprocessing.sequence.pad_sequences(X,maxlen=52,padding="post",value=0)

[array([26, 36, 26, 37, 26, 31, 36, 26])
 array([26, 36, 42, 48, 43, 34, 38, 26])
 array([26, 36, 37,  0, 39, 48, 26]) ...
 array([47, 34, 17, 26, 50, 26, 38])
 array([47, 30, 21, 43, 24, 46, 38, 20, 36, 26, 38])
 array([33, 34, 41, 39, 24,  0, 45, 34, 28, 26, 38])]


In [ ]:
X[0]

array([26, 36, 26, 37, 26, 31, 36, 26])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_train_val, y_train, y_train_val = train_test_split(X_train,df.sentiment,random_state=42,train_size=0.9)

In [ ]:
print(X_train)

[[39 30 21 ...  0  0  0]
 [47 34 35 ...  0  0  0]
 [44 47  8 ...  0  0  0]
 ...
 [41 43  0 ...  0  0  0]
 [41  0 27 ...  0  0  0]
 [41 30 21 ...  0  0  0]]


In [ ]:
embedding_weights=[]
for i in d:
  embedding_weights.append(d[i])
embedding_weights=np.array(embedding_weights)

In [ ]:
embedding_weights[0]

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
df_hindi=prepare_dataset("HN","hin")

agrima
acUka
acCA
acCI_waraha_se_calAne
acCI_waraha_se_judZA


In [ ]:
X=extract(df_hindi)
X_test=tf.keras.preprocessing.sequence.pad_sequences(X,maxlen=52,padding="post")
y_test=df_hindi.sentiment
X_test, X_test_val, y_test, y_test_val = train_test_split(X_test,y_test,random_state=42,train_size=0.9)

In [ ]:
y_test.shape

(4485,)

In [ ]:

# Include the epoch in the file name (uses `str.format`)
checkpoint_path = "training_2/cp-{epoch:04d}.ckpt"
checkpoint_dir = os.path.dirname(checkpoint_path)

# Create a callback that saves the model's weights every 5 epochs
cp_callback = tf.keras.callbacks.ModelCheckpoint(
    filepath=checkpoint_path, 
    verbose=1, 
    save_weights_only=True,
    save_freq=1)

In [ ]:
#using CNN
model=tf.keras.Sequential()
model.add(layer=tf.keras.layers.Embedding(52,52,weights=[embedding_weights],name="embedding"))
model.add(tf.keras.layers.Conv1D(350,4))
model.add(tf.keras.layers.BatchNormalization())
model.add(tf.keras.layers.GlobalMaxPooling1D())
model.add(tf.keras.layers.Dense(350))
model.add(tf.keras.layers.Dropout(0.5))
model.add(tf.keras.layers.Dense(3,activation='softmax'))

In [ ]:
model.compile(loss='sparse_categorical_crossentropy',
              optimizer=tf.keras.optimizers.Adam(),
              metrics=['accuracy'])

In [ ]:
model.save_weights(checkpoint_path.format(epoch=0))

In [ ]:
history=model.fit(X_train,y_train,epochs=3,validation_data=(X_test_val,y_test_val),callbacks=[cp_callback])

Epoch 1/3

Epoch 00001: saving model to training_2/cp-0001.ckpt
  1/398 [..............................] - ETA: 0s - loss: 4.8374 - accuracy: 0.4062
Epoch 00001: saving model to training_2/cp-0001.ckpt

Epoch 00001: saving model to training_2/cp-0001.ckpt
  3/398 [..............................] - ETA: 16s - loss: 6.6970 - accuracy: 0.4062
Epoch 00001: saving model to training_2/cp-0001.ckpt
  4/398 [..............................] - ETA: 20s - loss: 5.5913 - accuracy: 0.4062
Epoch 00001: saving model to training_2/cp-0001.ckpt

Epoch 00001: saving model to training_2/cp-0001.ckpt
  6/398 [..............................] - ETA: 21s - loss: 5.7839 - accuracy: 0.4531
Epoch 00001: saving model to training_2/cp-0001.ckpt
  7/398 [..............................] - ETA: 22s - loss: 5.7680 - accuracy: 0.4375
Epoch 00001: saving model to training_2/cp-0001.ckpt

Epoch 00001: saving model to training_2/cp-0001.ckpt
  9/398 [..............................] - ETA: 22s - loss: 5.6785 - accuracy: 0

In [ ]:
for i in range(1,4):
  if i<10:
    num="0"+str(i)
  else:
    num=str(i)
  s="training_2/cp-00"+num+".ckpt"
  model.load_weights(s)
  test_loss, test_acc = model.evaluate(X_test,y_test)
  print('Test Accuracy: {}'.format(test_acc))

141/141 [==============================] - 0s 2ms/step - loss: 0.9428 - accuracy: 0.4676
Test Accuracy: 0.46755853295326233
141/141 [==============================] - 0s 2ms/step - loss: 0.9549 - accuracy: 0.5295
Test Accuracy: 0.5295429229736328
141/141 [==============================] - 0s 2ms/step - loss: 0.8794 - accuracy: 0.5556
Test Accuracy: 0.5556298494338989


In [ ]:
weights=model.get_layer('embedding').get_weights()[0]
print(weights)

[[ 9.7622889e-01 -3.8967584e-03 -5.0298981e-02 ...  1.3677726e-02
  -2.1537030e-02  2.9012986e-02]
 [ 2.4080051e-02  9.6933347e-01  1.2837766e-02 ...  1.7960629e-06
   1.2262200e-02  2.0793188e-02]
 [ 1.7464358e-02 -1.0600800e-02  1.0042394e+00 ...  2.9668929e-02
   1.2323752e-02  3.1331558e-02]
 ...
 [-1.7132977e-02  1.7223479e-02 -1.8184850e-03 ...  9.6991700e-01
   1.5451790e-02 -1.3202721e-02]
 [ 1.0369446e-02  1.5193589e-03 -2.4819827e-02 ...  1.3389057e-02
   9.0600061e-01 -1.5270534e-03]
 [ 1.1013173e-02  2.7205637e-02 -2.1015166e-03 ... -9.2368312e-03
   2.9747991e-02  9.7192031e-01]]


In [ ]:
weight_mapping = []
chars="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
char_dict={chars[i]:i for i in range(len(chars))}

for i in range(0,52):
  weight_mapping.append(weights[i])
print()

In [ ]:
weight_mapping=np.array(weight_mapping)
embedding_weights.shape

(52, 52)

In [ ]:
df = load_dataset("review_sentiment.csv")

                                                text  polarity
0  Pesabuka kA sikyoritI cEkaapa PIcara pOYpaapa ...         0
1  isa pOYpaapa bOYksa meM pAsavarda ceMja karane...         0
2  Apa yahIM se purAne lOYgaina seSaMsa ko hameSA...         0
3  Ese meM kaI bAra EsA howA hE ki ApakA lOYgaina...         0
4  aba nae PIcara se isa waraha kI galawiyAM nahI...         1
5  eMdrOYyada  se Upara ke varjana para karawA hE...         0
6     eMdrOYyada  kitakEta yA usase Upara ke varj...         0
7  kaMpanI ke muwAbika  eMdrOYyada ke lie Ae peri...         1
8  periskopa ke eMdrOYyada varjana meM kuCa eVse ...         0
9  isameM meteriyala inspAyarda dijAina hE jo eMd...         0


In [ ]:
len(df.polarity)

5417

In [ ]:
X=[]

In [ ]:
weight_file = open("converted_sentence.bin","wb")

In [ ]:
for sentence in df.text:
  sentence.rstrip(". ?!")
  words=sentence.split(" ")
  arr=[]
  for word in words:
    for char in word:
      if char in chars:
        arr.append(char_dict[char])
  for i in range(52-len(arr)):
    arr.append(0)
  arr=arr[:52]
  arr=np.array(arr)
  X.append(arr)
X=np.asarray(X)
X.shape



(5417, 52)

In [ ]:
X[0]

array([41,  4, 18,  0,  1, 20, 10,  0, 10, 26, 18,  8, 10, 24, 14, 17,  8,
       19, 34,  2, 30, 10,  0,  0, 15,  0, 41, 34,  2,  0, 17,  0, 15, 40,
       50, 15,  0,  0, 15,  0, 10, 34, 22,  0, 17,  0,  7,  0, 24, 46,  9,
        0])

In [ ]:
#X=tf.keras.preprocessing.sequence.pad_sequences(X,maxlen=52,padding="post")
X_train, X_test, y_train, y_test = train_test_split(X,df.polarity,random_state=42,train_size=0.8)

In [ ]:
X_train[0]


array([11,  4, 10,  8, 13,  0, 49, 24, 26, 13,  0, 23,  4, 13,  4, 10, 34,
        1, 26, 22,  0, 24,  4,  7, 30, 10,  8,  1, 26,  9, 51, 26, 17,  0,
       12,  4, 38, 15, 34,  3,  8, 18, 15, 11,  4, 21, 26, 11,  4, 19,  4,
        1])

In [ ]:
print(X_test.shape,y_test.shape)

(1084, 52) (1084,)


In [ ]:
checkpoint_path = "training_3/cp-{epoch:04d}.ckpt"
checkpoint_dir = os.path.dirname(checkpoint_path)

# Create a callback that saves the model's weights every 5 epochs
cp_callback = tf.keras.callbacks.ModelCheckpoint(
    filepath=checkpoint_path, 
    verbose=1, 
    save_weights_only=True,
    save_freq=1)

In [ ]:
model=tf.keras.Sequential()
model.add(layer=tf.keras.layers.Embedding(52,52,weights=[weight_mapping]))
model.add(tf.keras.layers.Conv1D(350,4))
model.add(tf.keras.layers.BatchNormalization())
model.add(tf.keras.layers.GlobalMaxPooling1D())
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(350))
model.add(tf.keras.layers.Dropout(0.5))
model.add(tf.keras.layers.Dense(4,activation='softmax'))

In [ ]:
model.compile(loss='sparse_categorical_crossentropy',
              optimizer=tf.keras.optimizers.Adam(),
              metrics=['accuracy'])

In [ ]:
model.save_weights(checkpoint_path.format(epoch=0))

In [ ]:
X_test, X_test_val, y_test, y_test_val = train_test_split(X_test,y_test,random_state=42,train_size=0.9)

In [ ]:
model.fit(X_train,y_train,epochs=2,callbacks=[cp_callback],validation_data=(X_test_val,y_test_val))


Epoch 1/2

Epoch 00001: saving model to training_3/cp-0001.ckpt
  1/136 [..............................] - ETA: 0s - loss: 0.7471 - accuracy: 0.6250
Epoch 00001: saving model to training_3/cp-0001.ckpt

Epoch 00001: saving model to training_3/cp-0001.ckpt
  3/136 [..............................] - ETA: 5s - loss: 0.7096 - accuracy: 0.6771
Epoch 00001: saving model to training_3/cp-0001.ckpt
  4/136 [..............................] - ETA: 6s - loss: 0.7028 - accuracy: 0.6953
Epoch 00001: saving model to training_3/cp-0001.ckpt

Epoch 00001: saving model to training_3/cp-0001.ckpt
  6/136 [>.............................] - ETA: 7s - loss: 0.6819 - accuracy: 0.7135
Epoch 00001: saving model to training_3/cp-0001.ckpt
  7/136 [>.............................] - ETA: 7s - loss: 0.7210 - accuracy: 0.6964
Epoch 00001: saving model to training_3/cp-0001.ckpt

Epoch 00001: saving model to training_3/cp-0001.ckpt
  9/136 [>.............................] - ETA: 7s - loss: 0.6980 - accuracy: 0.7014

In [ ]:
for i in range(1,3):
  if i<10:
    num="0"+str(i)
  else:
    num=str(i)
  s="training_3/cp-00"+num+".ckpt"
  model.load_weights(s)
  test_loss, test_acc = model.evaluate(X_test,y_test)
  print('Test Accuracy: {}'.format(test_acc))

31/31 [==============================] - 0s 2ms/step - loss: 1.1711 - accuracy: 0.5877
Test Accuracy: 0.5876923203468323
31/31 [==============================] - 0s 2ms/step - loss: 1.1459 - accuracy: 0.5456
Test Accuracy: 0.5456410050392151


In [ ]:
model=tf.keras.Sequential()
model.add(tf.keras.layers.Embedding(52,52,weights=[embedding_weights]))
model.add(tf.compat.v1.keras.layers.CuDNNLSTM(52,return_sequences=True))
model.add(tf.keras.layers.Dropout(0.5))
model.add(tf.keras.layers.Dense(300))
model.add(tf.compat.v1.keras.layers.CuDNNLSTM(52,return_sequences=False))
model.add(tf.keras.layers.Dropout(0.5))
model.add(tf.keras.layers.Dense(100))
model.add(tf.keras.layers.Dense(4,activation='softmax'))

In [ ]:
model.compile(loss='sparse_categorical_crossentropy',
              optimizer=tf.keras.optimizers.Adam(),
              metrics=['accuracy'])

In [ ]:
model.save_weights(checkpoint_path.format(epoch=0))

In [ ]:
model.fit(X_train,y_train,epochs=4,callbacks=[cp_callback],validation_data=(X_test_val,y_test_val))

Epoch 1/4

Epoch 00001: saving model to training_3/cp-0001.ckpt
  1/136 [..............................] - ETA: 0s - loss: 0.9843 - accuracy: 0.5938
Epoch 00001: saving model to training_3/cp-0001.ckpt

Epoch 00001: saving model to training_3/cp-0001.ckpt
  3/136 [..............................] - ETA: 3s - loss: 0.9833 - accuracy: 0.5417
Epoch 00001: saving model to training_3/cp-0001.ckpt

Epoch 00001: saving model to training_3/cp-0001.ckpt
  5/136 [>.............................] - ETA: 4s - loss: 1.0245 - accuracy: 0.5375
Epoch 00001: saving model to training_3/cp-0001.ckpt

Epoch 00001: saving model to training_3/cp-0001.ckpt
  7/136 [>.............................] - ETA: 4s - loss: 1.0331 - accuracy: 0.5312
Epoch 00001: saving model to training_3/cp-0001.ckpt

Epoch 00001: saving model to training_3/cp-0001.ckpt
  9/136 [>.............................] - ETA: 4s - loss: 1.0489 - accuracy: 0.5104
Epoch 00001: saving model to training_3/cp-0001.ckpt

Epoch 00001: saving model to 

In [ ]:
for i in range(1,4):
  if i<10:
    num="0"+str(i)
  else:
    num=str(i)
  s="training_3/cp-00"+num+".ckpt"
  model.load_weights(s)
  test_loss, test_acc = model.evaluate(X_test,y_test)
  print('Test Accuracy: {}'.format(test_acc))

31/31 [==============================] - 0s 7ms/step - loss: 1.0777 - accuracy: 0.4687
Test Accuracy: 0.4687179625034332
31/31 [==============================] - 0s 6ms/step - loss: 1.0841 - accuracy: 0.5374
Test Accuracy: 0.5374358892440796
31/31 [==============================] - 0s 6ms/step - loss: 1.0818 - accuracy: 0.5087
Test Accuracy: 0.508717954158783


In [ ]:
#using RNN
model=tf.keras.Sequential()
model.add(tf.keras.layers.Embedding(52,52,weights=[embedding_weights]))
model.add(tf.keras.layers.LSTM(52,return_sequences=True))
model.add(tf.keras.layers.Dropout(0.1))
model.add(tf.keras.layers.LSTM(52,activation='relu'))
model.add(tf.keras.layers.Dropout(0.1))
model.add(tf.keras.layers.Dense(350))
model.add(tf.keras.layers.Dense(4,activation='softmax'))

In [ ]:
model.compile(loss='sparse_categorical_crossentropy',
              optimizer=tf.keras.optimizers.Adam(),
              metrics=['accuracy'])
model.save_weights(checkpoint_path.format(epoch=0))

In [ ]:
model.fit(X_train,y_train,epochs=4,callbacks=[cp_callback],validation_data=(X_test_val,y_test_val))

Epoch 1/4

Epoch 00001: saving model to training_3/cp-0001.ckpt
  1/136 [..............................] - ETA: 0s - loss: 1.3883 - accuracy: 0.1562
Epoch 00001: saving model to training_3/cp-0001.ckpt
  2/136 [..............................] - ETA: 7s - loss: 1.3805 - accuracy: 0.2969
Epoch 00001: saving model to training_3/cp-0001.ckpt
  3/136 [..............................] - ETA: 9s - loss: 1.3758 - accuracy: 0.2917
Epoch 00001: saving model to training_3/cp-0001.ckpt
  4/136 [..............................] - ETA: 10s - loss: 1.3649 - accuracy: 0.3906
Epoch 00001: saving model to training_3/cp-0001.ckpt
  5/136 [>.............................] - ETA: 10s - loss: 1.3546 - accuracy: 0.4375
Epoch 00001: saving model to training_3/cp-0001.ckpt
  6/136 [>.............................] - ETA: 11s - loss: 1.3456 - accuracy: 0.4479
Epoch 00001: saving model to training_3/cp-0001.ckpt
  7/136 [>.............................] - ETA: 11s - loss: 1.3362 - accuracy: 0.4598
Epoch 00001: saving

In [ ]:
for i in range(1,4):
  if i<10:
    num="0"+str(i)
  else:
    num=str(i)
  s="training_3/cp-00"+num+".ckpt"
  model.load_weights(s)
  test_loss, test_acc = model.evaluate(X_test,y_test)
  print('Test Accuracy: {}'.format(test_acc))

31/31 [==============================] - 0s 10ms/step - loss: 1.0953 - accuracy: 0.4503
Test Accuracy: 0.4502564072608948
31/31 [==============================] - 0s 9ms/step - loss: 1.1133 - accuracy: 0.4944
Test Accuracy: 0.49435898661613464
31/31 [==============================] - 0s 10ms/step - loss: 1.0777 - accuracy: 0.4687
Test Accuracy: 0.4687179625034332


In [ ]:
#using modified CNN_GRU
model = tf.keras.Sequential()
model.add(tf.keras.layers.Embedding(52,52,weights=[embedding_weights]))
model.add(tf.keras.layers.SpatialDropout1D(0.2)) # add spatial dropout
model.add(tf.keras.layers.Conv1D(52, 5, activation='relu')) # increase kernel size to 5
model.add(tf.keras.layers.MaxPooling1D(4))
model.add(tf.keras.layers.BatchNormalization()) # add batch normalization
model.add(tf.keras.layers.Dropout(0.1))
# modify to CuDNNGRU
#model.add(GRU(64, dropout=0.1, recurrent_dropout=0.5)) # defaults inclide tanh activation
model.add(tf.compat.v1.keras.layers.CuDNNGRU(64)) # does not have a dropout or recurrent dropout param
model.add(tf.keras.layers.BatchNormalization())
model.add(tf.keras.layers.Dropout(0.1))
model.add(tf.keras.layers.Dense(4, activation='softmax'))

In [ ]:
model.compile(loss='sparse_categorical_crossentropy',
              optimizer=tf.keras.optimizers.Adam(),
              metrics=['accuracy'])
model.save_weights(checkpoint_path.format(epoch=0))

In [ ]:
model.fit(X_train,y_train,epochs=20,validation_data=(X_train_val,y_train_val),callbacks=[cp_callback])

Streaming output truncated to the last 5000 lines.
Epoch 00002: saving model to training_3/cp-0002.ckpt

Epoch 00002: saving model to training_3/cp-0002.ckpt
104/136 [=====================>........] - ETA: 0s - loss: 1.1640 - accuracy: 0.4591
Epoch 00002: saving model to training_3/cp-0002.ckpt

Epoch 00002: saving model to training_3/cp-0002.ckpt
106/136 [======================>.......] - ETA: 0s - loss: 1.1621 - accuracy: 0.4593
Epoch 00002: saving model to training_3/cp-0002.ckpt

Epoch 00002: saving model to training_3/cp-0002.ckpt
108/136 [======================>.......] - ETA: 0s - loss: 1.1615 - accuracy: 0.4592
Epoch 00002: saving model to training_3/cp-0002.ckpt

Epoch 00002: saving model to training_3/cp-0002.ckpt
110/136 [=======================>......] - ETA: 0s - loss: 1.1603 - accuracy: 0.4599
Epoch 00002: saving model to training_3/cp-0002.ckpt

Epoch 00002: saving model to training_3/cp-0002.ckpt
112/136 [=======================>......] - ETA: 0s - loss: 1.1595 - accura

In [ ]:
for i in range(1,21):
  if i<10:
    num="0"+str(i)
  else:
    num=str(i)
  s="training_3/cp-00"+num+".ckpt"
  model.load_weights(s)
  test_loss, test_acc = model.evaluate(X_test,y_test)
  print('Test Accuracy: {}'.format(test_acc))

31/31 [==============================] - 2s 57ms/step - loss: 1.1393 - accuracy: 0.4574
Test Accuracy: 0.4574359059333801
31/31 [==============================] - 0s 3ms/step - loss: 1.0834 - accuracy: 0.5108
Test Accuracy: 0.510769248008728
31/31 [==============================] - 0s 3ms/step - loss: 1.0710 - accuracy: 0.4790
Test Accuracy: 0.4789743721485138
31/31 [==============================] - 0s 3ms/step - loss: 1.0449 - accuracy: 0.5262
Test Accuracy: 0.5261538624763489
31/31 [==============================] - 0s 3ms/step - loss: 1.0380 - accuracy: 0.5477
Test Accuracy: 0.5476922988891602
31/31 [==============================] - 0s 3ms/step - loss: 1.0171 - accuracy: 0.5733
Test Accuracy: 0.5733333230018616
31/31 [==============================] - 0s 3ms/step - loss: 1.0162 - accuracy: 0.5508
Test Accuracy: 0.5507692098617554
31/31 [==============================] - 0s 3ms/step - loss: 1.0470 - accuracy: 0.5610
Test Accuracy: 0.5610256195068359
31/31 [=========================

In [ ]:
model = tf.keras.Sequential()
layer=tf.keras.layers.Embedding(52,52,input_length=52)
model.add(layer)
model.add(tf.keras.layers.Conv1D(52, 3))
model.add(tf.keras.layers.SpatialDropout1D(0.01))
model.add(tf.keras.layers.MaxPooling1D(4))
model.add(tf.compat.v1.keras.layers.CuDNNLSTM(64))
model.add(tf.keras.layers.Dropout(0.01))
model.add(tf.keras.layers.Dense(4, activation='softmax'))

In [ ]:
model.compile(loss='sparse_categorical_crossentropy',
              optimizer=tf.keras.optimizers.Adam(),
              metrics=['accuracy'])
model.save_weights(checkpoint_path.format(epoch=0))

In [ ]:
model.fit(X_train,y_train,epochs=20,callbacks=[cp_callback],validation_data=(X_test_val,y_test_val))

Streaming output truncated to the last 5000 lines.
Epoch 00002: saving model to training_3/cp-0002.ckpt

Epoch 00002: saving model to training_3/cp-0002.ckpt

Epoch 00002: saving model to training_3/cp-0002.ckpt
105/136 [======================>.......] - ETA: 0s - loss: 1.0893 - accuracy: 0.4664
Epoch 00002: saving model to training_3/cp-0002.ckpt

Epoch 00002: saving model to training_3/cp-0002.ckpt

Epoch 00002: saving model to training_3/cp-0002.ckpt
108/136 [======================>.......] - ETA: 0s - loss: 1.0890 - accuracy: 0.4661
Epoch 00002: saving model to training_3/cp-0002.ckpt

Epoch 00002: saving model to training_3/cp-0002.ckpt

Epoch 00002: saving model to training_3/cp-0002.ckpt
111/136 [=======================>......] - ETA: 0s - loss: 1.0898 - accuracy: 0.4659
Epoch 00002: saving model to training_3/cp-0002.ckpt

Epoch 00002: saving model to training_3/cp-0002.ckpt

Epoch 00002: saving model to training_3/cp-0002.ckpt
114/136 [========================>.....] - ETA: 0s

In [ ]:
for i in range(1,21):
  if i<10:
    num="0"+str(i)
  else:
    num=str(i)
  s="training_3/cp-00"+num+".ckpt"
  model.load_weights(s)
  test_loss, test_acc = model.evaluate(X_test,y_test)
  print('Test Accuracy: {}'.format(test_acc))

31/31 [==============================] - 2s 58ms/step - loss: 1.1021 - accuracy: 0.4646
Test Accuracy: 0.4646153748035431
31/31 [==============================] - 0s 2ms/step - loss: 1.0548 - accuracy: 0.5282
Test Accuracy: 0.528205156326294
31/31 [==============================] - 0s 2ms/step - loss: 1.0898 - accuracy: 0.5241
Test Accuracy: 0.5241025686264038
31/31 [==============================] - 0s 2ms/step - loss: 1.0227 - accuracy: 0.5395
Test Accuracy: 0.5394871830940247
31/31 [==============================] - 0s 3ms/step - loss: 1.0430 - accuracy: 0.5221
Test Accuracy: 0.5220512747764587
31/31 [==============================] - 0s 2ms/step - loss: 1.0073 - accuracy: 0.5456
Test Accuracy: 0.5456410050392151
31/31 [==============================] - 0s 2ms/step - loss: 1.0178 - accuracy: 0.5528
Test Accuracy: 0.5528205037117004
31/31 [==============================] - 0s 2ms/step - loss: 1.0965 - accuracy: 0.5179
Test Accuracy: 0.5179487466812134
31/31 [=========================

In [ ]:
#BiGRU
model = tf.keras.Sequential()
model.add(tf.keras.layers.Embedding(52,52,weights=[embedding_weights]))
model.add(tf.keras.layers.Bidirectional(tf.compat.v1.keras.layers.CuDNNGRU(52)))
model.add(tf.keras.layers.Dropout(0.1))
model.add(tf.keras.layers.Dense(350))
model.add(tf.keras.layers.Dense(4,activation='softmax'))

In [ ]:
model.compile(loss='sparse_categorical_crossentropy',
              optimizer=tf.keras.optimizers.Adam(),
              metrics=['accuracy'])
model.save_weights(checkpoint_path.format(epoch=0))

In [ ]:
model.fit(X_train,y_train,epochs=10,callbacks=[cp_callback],validation_data=(X_test_val,y_test_val))

Epoch 1/10

Epoch 00001: saving model to training_3/cp-0001.ckpt
  1/136 [..............................] - ETA: 0s - loss: 0.9117 - accuracy: 0.6562
Epoch 00001: saving model to training_3/cp-0001.ckpt

Epoch 00001: saving model to training_3/cp-0001.ckpt
  3/136 [..............................] - ETA: 2s - loss: 0.7942 - accuracy: 0.6667
Epoch 00001: saving model to training_3/cp-0001.ckpt

Epoch 00001: saving model to training_3/cp-0001.ckpt
  5/136 [>.............................] - ETA: 3s - loss: 0.8225 - accuracy: 0.6625
Epoch 00001: saving model to training_3/cp-0001.ckpt

Epoch 00001: saving model to training_3/cp-0001.ckpt
  7/136 [>.............................] - ETA: 3s - loss: 0.8171 - accuracy: 0.6607
Epoch 00001: saving model to training_3/cp-0001.ckpt

Epoch 00001: saving model to training_3/cp-0001.ckpt
  9/136 [>.............................] - ETA: 3s - loss: 0.8134 - accuracy: 0.6562
Epoch 00001: saving model to training_3/cp-0001.ckpt

Epoch 00001: saving model to

In [ ]:
for i in range(1,21):
  if i<10:
    num="0"+str(i)
  else:
    num=str(i)
  s="training_3/cp-00"+num+".ckpt"
  model.load_weights(s)
  test_loss, test_acc = model.evaluate(X_test,y_test)
  print('Test Accuracy: {}'.format(test_acc))

31/31 [==============================] - 0s 5ms/step - loss: 1.1584 - accuracy: 0.5149
Test Accuracy: 0.5148717761039734
31/31 [==============================] - 0s 4ms/step - loss: 1.1904 - accuracy: 0.5015
Test Accuracy: 0.5015384554862976
31/31 [==============================] - 0s 5ms/step - loss: 1.2112 - accuracy: 0.5251
Test Accuracy: 0.525128185749054
31/31 [==============================] - 0s 4ms/step - loss: 1.2348 - accuracy: 0.5221
Test Accuracy: 0.5220512747764587
31/31 [==============================] - 0s 5ms/step - loss: 1.2208 - accuracy: 0.5282
Test Accuracy: 0.528205156326294
31/31 [==============================] - 0s 5ms/step - loss: 1.2834 - accuracy: 0.5323
Test Accuracy: 0.5323076844215393
31/31 [==============================] - 0s 5ms/step - loss: 1.3301 - accuracy: 0.4995
Test Accuracy: 0.4994871914386749
31/31 [==============================] - 0s 5ms/step - loss: 1.3960 - accuracy: 0.5169
Test Accuracy: 0.5169230699539185
31/31 [===========================

In [ ]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Embedding(52,52,weights=[embedding_weights]))
model.add(tf.compat.v1.keras.layers.CuDNNGRU(52))
model.add(tf.keras.layers.Dropout(0.1))
model.add(tf.keras.layers.Dense(350))
model.add(tf.keras.layers.Dense(4,activation='softmax'))

In [ ]:
model.compile(loss='sparse_categorical_crossentropy',
              optimizer=tf.keras.optimizers.Adam(),
              metrics=['accuracy'])

In [ ]:
model.save_weights(checkpoint_path.format(epoch=0))

In [ ]:
history=model.fit(X_train,y_train,epochs=20,validation_data=(X_test_val,y_test_val), callbacks=[cp_callback])

Streaming output truncated to the last 5000 lines.
Epoch 00002: saving model to training_3/cp-0002.ckpt
103/136 [=====================>........] - ETA: 0s - loss: 0.8600 - accuracy: 0.6126
Epoch 00002: saving model to training_3/cp-0002.ckpt

Epoch 00002: saving model to training_3/cp-0002.ckpt

Epoch 00002: saving model to training_3/cp-0002.ckpt
106/136 [======================>.......] - ETA: 0s - loss: 0.8587 - accuracy: 0.6135
Epoch 00002: saving model to training_3/cp-0002.ckpt

Epoch 00002: saving model to training_3/cp-0002.ckpt

Epoch 00002: saving model to training_3/cp-0002.ckpt
109/136 [=======================>......] - ETA: 0s - loss: 0.8575 - accuracy: 0.6147
Epoch 00002: saving model to training_3/cp-0002.ckpt

Epoch 00002: saving model to training_3/cp-0002.ckpt

Epoch 00002: saving model to training_3/cp-0002.ckpt
112/136 [=======================>......] - ETA: 0s - loss: 0.8590 - accuracy: 0.6138
Epoch 00002: saving model to training_3/cp-0002.ckpt

Epoch 00002: saving

In [ ]:
for i in range(1,21):
  if i<10:
    num="0"+str(i)
  else:
    num=str(i)
  s="training_3/cp-00"+num+".ckpt"
  model.load_weights(s)
  test_loss, test_acc = model.evaluate(X_test,y_test)
  print('Test Accuracy: {}'.format(test_acc))

31/31 [==============================] - 0s 3ms/step - loss: 1.0538 - accuracy: 0.5446
Test Accuracy: 0.5446153879165649
31/31 [==============================] - 0s 3ms/step - loss: 1.0912 - accuracy: 0.5436
Test Accuracy: 0.5435897707939148
31/31 [==============================] - 0s 3ms/step - loss: 1.0681 - accuracy: 0.5395
Test Accuracy: 0.5394871830940247
31/31 [==============================] - 0s 3ms/step - loss: 1.0766 - accuracy: 0.5313
Test Accuracy: 0.5312820672988892
31/31 [==============================] - 0s 3ms/step - loss: 1.0918 - accuracy: 0.5303
Test Accuracy: 0.5302563905715942
31/31 [==============================] - 0s 3ms/step - loss: 1.0946 - accuracy: 0.5210
Test Accuracy: 0.5210256576538086
31/31 [==============================] - 0s 3ms/step - loss: 1.1196 - accuracy: 0.5436
Test Accuracy: 0.5435897707939148
31/31 [==============================] - 0s 3ms/step - loss: 1.1454 - accuracy: 0.5426
Test Accuracy: 0.5425640940666199
31/31 [=========================